import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../generated/prisma/client.js';

type CatalogMenu = {
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  category: string;
  cluster: 'western_indonesian' | 'chinese_food' | 'seafood';
  restaurant: string;
  tags: string[];
  allergens: string[];
  ingredients: string[];
  hiddenIngredients: string[];
  sensoryProfile: string[];
  crossContaminationRisk?: string;
  calories: number;

  prepMinutes: number;
  sourceUrl: string;
};

const photos = {
  rice: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=80',
  curry:
    'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',
  chicken:
    'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80',
  noodles:
    'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=80',
  soup: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80',
  salad:
    'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=80',
  steak:
    'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=80',
  burger:
    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',
  pasta:
    'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80',
  shrimp:
    'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=900&q=80',
  fish: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=80',
  crab: 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=900&q=80',
};

const sourceByRestaurant: Record<string, string> = {
  'Sate Khas Senayan': 'https://satekhas.sarirasa.co.id/menu',
  'Cinnamon - Mandarin Oriental Jakarta':
    'https://photos.mandarinoriental.com/is/content/MandarinOriental/jakarta-restaurant-cinnamon-menu',
  'Steak Hotel by HOLYCOW!':
    'https://www.holycowsteak.com/pages/menu-steak-hotel-by-holycow',
  'Pizza Marzano Indonesia': 'https://www.pizzamarzano.co.id/menu/main-menu/',
  'Bakmi GM': 'https://www.bakmigm.com/menu',
  'Ta Wan': 'https://www.tawanrestaurant.com/',
  'Imperial Kitchen & Dimsum':
    'https://www.impgroup.co.id/our-brands/imperial-kitchen-dimsum',
  'Bandar Djakarta': 'https://www.bandar-djakarta.com/bandar-djakarta-menu/',
  "D'Cost Seafood": 'https://dcostseafood.id/',
};

const sourceByMenu: Record<string, string> = {
  'Bakmi Spesial GM': 'https://www.bakmigm.com/bakmi-spesial-gm',
  'Nasi Ayam GM': 'https://www.bakmigm.com/nasi-ayam-gm',
  'Nasi Ayam Goreng Mentega':
    'https://www.bakmigm.com/nasi-ayam-goreng-mentega',
  'Udang Saus Padang': 'https://www.bandar-djakarta.com/menu-udang/',
  'Udang Bakar Madu Pedas': 'https://www.bandar-djakarta.com/menu-udang/',
  'Cumi Goreng Tepung': 'https://www.bandar-djakarta.com/menu-cumi-cumi/',
  'Ikan Bakar Bandar': 'https://www.bandar-djakarta.com/menu-ikan/',
  'Ikan Soup Kimlo': 'https://www.bandar-djakarta.com/menu-ikan/',
  'Kepiting Saus Lada Hitam': 'https://www.bandar-djakarta.com/menu-kepiting/',
  'Kerang Hijau Saos Padang': 'https://www.bandar-djakarta.com/menu-kerang/',
  'Lobster Bakar Madu': 'https://www.bandar-djakarta.com/menu-lobster/',
};

const officialPriceSnapshots = new Set([
  'Nasi Goreng Ayam',
  'Sate Ayam Campur Bumbu Blora',
  'Soto Ayam Ambengan',
  'Gado Gado',
  'Ayam Taliwang',
  'Pisang Goreng',
  'Telur Sutra Ebi',
  'Telur Sutra Ayam Cincang',
  'Telur Tomat Asam Manis',
  'Fish and Chips',
  'Nasi Ikan Patin Sambal Tempong',
  'Chicken Cordon Bleu',
]);

// Nilai sumber lama pada objek di bawah selalu ditimpa oleh sumber resmi
// berdasarkan restoran/menu sebelum upsert.
const mahi = '';
const royco = '';

const catalog: CatalogMenu[] = [
  // Western–Indonesian cluster
  {
    name: 'Nasi Goreng Ayam',
    description: 'Nasi wok smoky dengan ayam suwir, cabai, dan kecap manis.',
    price: 50000,
    imageUrl: photos.rice,
    category: 'main_course',
    cluster: 'western_indonesian',
    restaurant: 'Sate Khas Senayan',
    tags: ['halal', 'spicy'],
    allergens: ['telur', 'kedelai'],
    ingredients: ['nasi', 'ayam', 'telur', 'kecap manis', 'cabai'],
    hiddenIngredients: ['kecap mengandung kedelai'],
    sensoryProfile: ['smoky', 'gurih', 'pedas'],
    calories: 510,
    prepMinutes: 18,
    sourceUrl: royco,
  },
  {
    name: 'Rendang Sapi Minang',
    description:
      'Daging sapi empuk dengan santan dan rempah Minang yang pekat.',
    price: 42000,
    imageUrl: photos.curry,
    category: 'main_course',
    cluster: 'western_indonesian',
    restaurant: 'Cinnamon - Mandarin Oriental Jakarta',
    tags: ['halal', 'high_protein', 'low_carb'],
    allergens: [],
    ingredients: ['daging sapi', 'santan', 'cabai', 'serai', 'lengkuas'],
    hiddenIngredients: [],
    sensoryProfile: ['empuk', 'pekat', 'gurih', 'pedas'],
    calories: 468,
    prepMinutes: 35,
    sourceUrl: royco,
  },
  {
    name: 'Sate Ayam Campur Bumbu Blora',
    description: 'Sate ayam bakar harum dengan saus kacang manis gurih.',
    price: 66000,
    imageUrl: photos.chicken,
    category: 'main_course',
    cluster: 'western_indonesian',
    restaurant: 'Sate Khas Senayan',
    tags: ['halal', 'high_protein'],
    allergens: ['kacang', 'kedelai'],
    ingredients: ['ayam', 'kacang tanah', 'kecap manis', 'bawang'],
    hiddenIngredients: ['saus kacang', 'kecap mengandung kedelai'],
    sensoryProfile: ['smoky', 'gurih', 'manis'],
    calories: 430,
    prepMinutes: 25,
    sourceUrl: mahi,
  },
  {
    name: 'Soto Ayam Ambengan',
    description: 'Kuah kuning hangat, ayam suwir, koya, dan jeruk nipis segar.',
    price: 45000,
    imageUrl: photos.soup,
    category: 'soup',
    cluster: 'western_indonesian',
    restaurant: 'Sate Khas Senayan',
    tags: ['halal', 'high_protein'],
    allergens: ['telur', 'seafood'],
    ingredients: ['ayam', 'telur', 'bihun', 'kerupuk udang', 'koya'],
    hiddenIngredients: ['kerupuk udang pada koya'],
    sensoryProfile: ['hangat', 'segar', 'gurih'],
    calories: 395,
    prepMinutes: 20,
    sourceUrl: mahi,
  },
  {
    name: 'Gado Gado',
    description: 'Sayur rebus renyah, tahu, tempe, dan bumbu kacang creamy.',
    price: 55000,
    imageUrl: photos.salad,
    category: 'main_course',
    cluster: 'western_indonesian',
    restaurant: 'Sate Khas Senayan',
    tags: ['halal', 'vegetarian'],
    allergens: ['kacang', 'kedelai', 'telur'],
    ingredients: ['sayuran', 'tahu', 'tempe', 'telur', 'kacang tanah'],
    hiddenIngredients: ['kacang pada saus', 'kedelai pada tahu dan tempe'],
    sensoryProfile: ['creamy', 'renyah', 'gurih'],
    calories: 420,
    prepMinutes: 15,
    sourceUrl: mahi,
  },
  {
    name: 'Ayam Taliwang',
    description: 'Ayam bakar juicy dengan sambal Taliwang yang pedas berasap.',
    price: 75000,
    imageUrl: photos.chicken,
    category: 'main_course',
    cluster: 'western_indonesian',
    restaurant: 'Sate Khas Senayan',
    tags: ['halal', 'high_protein', 'low_carb', 'spicy'],
    allergens: [],
    ingredients: ['ayam', 'cabai', 'tomat', 'terasi'],
    hiddenIngredients: ['terasi fermentasi'],
    sensoryProfile: ['juicy', 'smoky', 'pedas'],
    calories: 380,
    prepMinutes: 28,
    sourceUrl: mahi,
  },
  {
    name: 'Australian Sirloin Steak',
    description:
      'Prime Australian beef 200 gram dengan kentang, tumis sayur, dan pilihan saus.',
    price: 52000,
    imageUrl: photos.steak,
    category: 'main_course',
    cluster: 'western_indonesian',
    restaurant: 'Steak Hotel by HOLYCOW!',
    tags: ['halal', 'high_protein'],
    allergens: ['susu'],
    ingredients: ['sirloin sapi Australia', 'kentang', 'sayuran', 'saus'],
    hiddenIngredients: ['mentega atau susu dapat terkandung pada saus'],
    sensoryProfile: ['juicy', 'smoky', 'gurih'],
    calories: 690,
    prepMinutes: 22,
    sourceUrl: 'https://www.allrecipes.com/recipes/473/main-dish/burgers/',
  },
  {
    name: 'Pollo e Porcini',
    description:
      'Pizza dengan ayam, jamur portobello, saus jamur, mozzarella, dan pesto.',
    price: 46000,
    imageUrl: photos.pasta,
    category: 'main_course',
    cluster: 'western_indonesian',
    restaurant: 'Pizza Marzano Indonesia',
    tags: ['high_protein'],
    allergens: ['susu', 'gluten', 'kacang'],
    ingredients: [
      'adonan pizza',
      'ayam',
      'jamur portobello',
      'mozzarella',
      'pesto',
    ],
    hiddenIngredients: [
      'susu pada mozzarella',
      'kacang dapat terkandung pada pesto',
    ],
    sensoryProfile: ['creamy', 'gurih', 'aromatik'],
    calories: 360,
    prepMinutes: 17,
    sourceUrl: 'https://www.allrecipes.com/recipes/2294/salad/caesar-salad/',
  },
  {
    name: 'Spaghetti Aglio Olio',
    description:
      'Pasta al dente dengan bawang putih, cabai, dan minyak zaitun.',
    price: 44000,
    imageUrl: photos.pasta,
    category: 'main_course',
    cluster: 'western_indonesian',
    restaurant: 'Pizza Marzano Indonesia',
    tags: ['vegetarian', 'spicy'],
    allergens: ['gluten'],
    ingredients: ['pasta gandum', 'bawang putih', 'minyak zaitun', 'cabai'],
    hiddenIngredients: ['gluten pada pasta'],
    sensoryProfile: ['al_dente', 'aromatik', 'pedas'],
    calories: 480,
    prepMinutes: 20,
    sourceUrl: 'https://www.allrecipes.com/recipes/502/main-dish/pasta/',
  },
  {
    name: 'Mushroom Dip & Flatbread',
    description:
      'Dip jamur, bechamel, minyak truffle, parmesan, dan garlic oil dengan flatbread panggang.',
    price: 32000,
    imageUrl: photos.soup,
    category: 'appetizer',
    cluster: 'western_indonesian',
    restaurant: 'Pizza Marzano Indonesia',
    tags: ['vegetarian'],
    allergens: ['susu', 'gluten'],
    ingredients: [
      'jamur',
      'bechamel',
      'minyak truffle',
      'parmesan',
      'flatbread',
    ],
    hiddenIngredients: [
      'susu pada bechamel dan parmesan',
      'gluten pada flatbread',
    ],
    sensoryProfile: ['hangat', 'creamy', 'aromatik'],
    calories: 290,
    prepMinutes: 18,
    sourceUrl:
      'https://www.allrecipes.com/recipes/16369/soups-stews-and-chili/soup/cream-soups/',
  },
  {
    name: 'Wagyu Sirloin Steak',
    description: 'Sirloin panggang juicy dengan saus lada hitam dan kentang.',
    price: 89000,
    imageUrl: photos.steak,
    category: 'main_course',
    cluster: 'western_indonesian',
    restaurant: 'Steak Hotel by HOLYCOW!',
    tags: ['halal', 'high_protein'],
    allergens: ['susu', 'kedelai'],
    ingredients: ['sirloin sapi', 'mentega', 'saus lada hitam', 'kentang'],
    hiddenIngredients: ['mentega pada basting', 'kecap asin pada saus'],
    sensoryProfile: ['juicy', 'smoky', 'pedas'],
    calories: 620,
    prepMinutes: 30,
    sourceUrl:
      'https://www.allrecipes.com/recipes/1232/meat-and-poultry/beef/steaks/',
  },
  {
    name: 'Pisang Goreng',
    description: 'Pisang goreng hangat yang disajikan dengan gula aren.',
    price: 22000,
    imageUrl: photos.curry,
    category: 'dessert',
    cluster: 'western_indonesian',
    restaurant: 'Sate Khas Senayan',
    tags: ['halal', 'vegetarian', 'sweet'],
    allergens: ['gluten'],
    ingredients: ['pisang', 'tepung terigu', 'gula aren'],
    hiddenIngredients: ['gluten pada adonan'],
    sensoryProfile: ['renyah', 'manis', 'hangat'],
    calories: 310,
    prepMinutes: 15,
    sourceUrl: royco,
  },

  // Chinese food cluster
  {
    name: 'Nasi Ayam Goreng Mentega',
    description: 'Ayam goreng juicy berselimut saus mentega gurih manis.',
    price: 43000,
    imageUrl: photos.chicken,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Bakmi GM',
    tags: ['halal', 'high_protein'],
    allergens: ['susu', 'kedelai'],
    ingredients: [
      'ayam',
      'mentega',
      'kecap manis',
      'kecap asin',
      'bawang bombay',
    ],
    hiddenIngredients: ['susu pada mentega', 'kedelai pada kecap'],
    sensoryProfile: ['juicy', 'gurih', 'manis'],
    calories: 540,
    prepMinutes: 25,
    sourceUrl:
      'https://www.masakapahariini.com/r/resep-ayam-saus-mentega-khas-restoran-chinese-food.html/257415',
  },
  {
    name: 'Cap Cay',
    description: 'Sayuran warna-warni yang renyah dengan kuah gurih tipis.',
    price: 36000,
    imageUrl: photos.salad,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Bakmi GM',
    tags: ['halal', 'low_fat'],
    allergens: ['seafood', 'kedelai'],
    ingredients: ['wortel', 'brokoli', 'sawi', 'bakso ikan', 'saus tiram'],
    hiddenIngredients: ['ekstrak seafood pada saus tiram', 'bakso ikan'],
    sensoryProfile: ['renyah', 'segar', 'gurih'],
    calories: 260,
    prepMinutes: 20,
    sourceUrl: mahi,
  },
  {
    name: 'Nasi Brokoli Sapi Lada Hitam',
    description:
      'Nasi dengan irisan sapi dan brokoli dalam saus lada hitam gurih.',
    price: 41000,
    imageUrl: photos.rice,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Bakmi GM',
    tags: ['halal', 'high_protein'],
    allergens: ['kedelai', 'seafood'],
    ingredients: [
      'nasi',
      'daging sapi',
      'brokoli',
      'saus lada hitam',
      'saus tiram',
    ],
    hiddenIngredients: ['ekstrak seafood pada saus tiram'],
    sensoryProfile: ['hangat', 'pedas', 'gurih'],
    calories: 575,
    prepMinutes: 22,
    sourceUrl: mahi,
  },
  {
    name: 'Fu Yung Hai',
    description:
      'Telur dadar tebal berisi ayam dan sayur dengan saus asam manis.',
    price: 39000,
    imageUrl: photos.rice,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Bakmi GM',
    tags: ['halal', 'high_protein'],
    allergens: ['telur', 'seafood'],
    ingredients: ['telur', 'ayam', 'kol', 'saus tomat', 'kaldu udang'],
    hiddenIngredients: ['kaldu udang pada saus'],
    sensoryProfile: ['lembut', 'asam_manis', 'gurih'],
    calories: 445,
    prepMinutes: 25,
    sourceUrl: mahi,
  },
  {
    name: 'Bakmi Spesial GM',
    description: 'Mi kenyal dengan ayam jamur kecap dan pangsit renyah.',
    price: 35000,
    imageUrl: photos.noodles,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Bakmi GM',
    tags: ['halal'],
    allergens: ['gluten', 'telur', 'kedelai'],
    ingredients: ['mi telur', 'ayam', 'jamur', 'kecap asin', 'pangsit'],
    hiddenIngredients: ['telur dan gluten pada mi'],
    sensoryProfile: ['kenyal', 'gurih', 'aromatik'],
    calories: 520,
    prepMinutes: 15,
    sourceUrl: mahi,
  },
  {
    name: 'Homemade Bean Curd with Shimeji Mushroom',
    description:
      'Tahu buatan rumah dengan jamur shimeji dan saus gurih ala Imperial.',
    price: 42000,
    imageUrl: photos.soup,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Imperial Kitchen & Dimsum',
    tags: ['halal', 'vegetarian'],
    allergens: ['kedelai', 'seafood'],
    ingredients: ['tahu', 'jamur shimeji', 'sayuran', 'saus tiram'],
    hiddenIngredients: ['kedelai pada tahu', 'ekstrak seafood pada saus tiram'],
    sensoryProfile: ['lembut', 'hangat', 'gurih'],
    calories: 380,
    prepMinutes: 24,
    sourceUrl: mahi,
  },
  {
    name: 'Telur Sutra Ebi',
    description:
      'Telur bertekstur sutra dengan ebi yang menghadirkan rasa laut lembut.',
    price: 39000,
    imageUrl: photos.shrimp,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Ta Wan',
    tags: ['halal', 'high_protein'],
    allergens: ['telur', 'seafood'],
    ingredients: ['telur', 'ebi', 'daun bawang', 'saus gurih'],
    hiddenIngredients: ['ebi adalah udang kering'],
    sensoryProfile: ['lembut', 'hangat', 'gurih'],
    calories: 560,
    prepMinutes: 25,
    sourceUrl: mahi,
  },
  {
    name: 'Telur Sutra Ayam Cincang',
    description:
      'Telur bertekstur sutra dengan ayam cincang yang hangat dan gurih.',
    price: 39000,
    imageUrl: photos.chicken,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Ta Wan',
    tags: ['halal', 'high_protein'],
    allergens: ['telur'],
    ingredients: ['telur', 'ayam cincang', 'daun bawang', 'saus gurih'],
    hiddenIngredients: [],
    sensoryProfile: ['lembut', 'hangat', 'gurih'],
    calories: 300,
    prepMinutes: 18,
    sourceUrl: mahi,
  },
  {
    name: 'Telur Tomat Asam Manis',
    description:
      'Telur lembut dengan tomat dalam saus asam manis yang ringan dan segar.',
    price: 39000,
    imageUrl: photos.rice,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Ta Wan',
    tags: ['halal'],
    allergens: ['telur'],
    ingredients: ['telur', 'tomat', 'saus asam manis', 'daun bawang'],
    hiddenIngredients: [],
    sensoryProfile: ['lembut', 'asam_manis', 'segar'],
    calories: 590,
    prepMinutes: 28,
    sourceUrl:
      'https://www.masakapahariini.com/r/resep-ayam-tepung-asam-manis-a-la-restoran.html/257423',
  },
  {
    name: 'Deep Fried Spicy Chicken with Garlic',
    description:
      'Ayam goreng renyah dengan bawang putih dan cabai ala Imperial.',
    price: 37000,
    imageUrl: photos.chicken,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Imperial Kitchen & Dimsum',
    tags: ['halal', 'high_protein', 'spicy'],
    allergens: ['gluten'],
    ingredients: ['ayam', 'tepung terigu', 'bawang putih', 'cabai'],
    hiddenIngredients: ['gluten pada lapisan tepung'],
    sensoryProfile: ['renyah', 'pedas', 'aromatik'],
    calories: 410,
    prepMinutes: 20,
    sourceUrl: mahi,
  },
  {
    name: 'Nasi Ayam GM',
    description: 'Nasi dengan ayam dan jamur khas GM, dilengkapi kuah gurih.',
    price: 29000,
    imageUrl: photos.rice,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Bakmi GM',
    tags: ['halal'],
    allergens: ['kedelai'],
    ingredients: ['nasi', 'ayam', 'jamur', 'saus khas GM', 'kuah'],
    hiddenIngredients: ['kedelai dapat terkandung pada saus khas GM'],
    sensoryProfile: ['hangat', 'lembut', 'gurih'],
    calories: 420,
    prepMinutes: 16,
    sourceUrl: mahi,
  },
  {
    name: 'Signature Roasted Duck',
    description:
      'Bebek panggang signature dengan kulit renyah dan daging gurih.',
    price: 26000,
    imageUrl: photos.curry,
    category: 'main_course',
    cluster: 'chinese_food',
    restaurant: 'Imperial Kitchen & Dimsum',
    tags: ['high_protein'],
    allergens: ['kedelai'],
    ingredients: ['bebek', 'bumbu panggang', 'kecap asin'],
    hiddenIngredients: ['kedelai pada kecap asin'],
    sensoryProfile: ['renyah', 'juicy', 'gurih'],
    calories: 280,
    prepMinutes: 15,
    sourceUrl: mahi,
  },

  // Seafood cluster
  {
    name: 'Udang Saus Padang',
    description: 'Udang segar dengan saus Padang pedas, kental, dan harum.',
    price: 68000,
    imageUrl: photos.shrimp,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: 'Bandar Djakarta',
    tags: ['halal', 'high_protein', 'spicy'],
    allergens: ['seafood', 'telur', 'kedelai'],
    ingredients: ['udang', 'saus tomat', 'saus tiram', 'telur', 'cabai'],
    hiddenIngredients: ['telur sebagai pengental', 'kedelai pada saus'],
    sensoryProfile: ['juicy', 'pedas', 'gurih'],
    crossContaminationRisk:
      'Dimasak di wok yang juga menangani kepiting dan cumi.',
    calories: 430,
    prepMinutes: 25,
    sourceUrl: mahi,
  },
  {
    name: 'Cumi Goreng Tepung',
    description: 'Cincin cumi berbalut tepung ringan yang garing dan gurih.',
    price: 59000,
    imageUrl: photos.shrimp,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: 'Bandar Djakarta',
    tags: ['halal', 'high_protein'],
    allergens: ['seafood', 'gluten', 'telur'],
    ingredients: ['cumi', 'tepung terigu', 'telur', 'lada'],
    hiddenIngredients: ['telur pada batter'],
    sensoryProfile: ['renyah', 'kenyal', 'gurih'],
    crossContaminationRisk: 'Menggunakan fryer bersama menu udang.',
    calories: 510,
    prepMinutes: 20,
    sourceUrl: mahi,
  },
  {
    name: 'Ikan Bakar Bandar',
    description:
      'Ikan laut bakar dengan bumbu merah manis pedas dan jeruk limau.',
    price: 75000,
    imageUrl: photos.fish,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: 'Bandar Djakarta',
    tags: ['halal', 'high_protein', 'low_carb'],
    allergens: ['seafood', 'kedelai'],
    ingredients: ['ikan kakap', 'kecap manis', 'cabai', 'jeruk limau'],
    hiddenIngredients: ['kedelai pada kecap'],
    sensoryProfile: ['smoky', 'juicy', 'pedas'],
    crossContaminationRisk: 'Panggangan digunakan bersama kerang dan udang.',
    calories: 390,
    prepMinutes: 32,
    sourceUrl: mahi,
  },
  {
    name: 'Kepiting Saus Lada Hitam',
    description: 'Kepiting manis alami dengan saus lada hitam yang tajam.',
    price: 145000,
    imageUrl: photos.crab,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: 'Bandar Djakarta',
    tags: ['halal', 'high_protein', 'spicy'],
    allergens: ['seafood', 'kedelai'],
    ingredients: ['kepiting', 'lada hitam', 'saus tiram', 'kecap asin'],
    hiddenIngredients: ['ekstrak seafood pada saus tiram'],
    sensoryProfile: ['juicy', 'pedas', 'gurih'],
    crossContaminationRisk: 'Area preparasi khusus shellfish.',
    calories: 520,
    prepMinutes: 38,
    sourceUrl: mahi,
  },
  {
    name: 'Kerang Hijau Saos Padang',
    description: 'Kerang hijau kenyal dengan saus Padang pedas dan gurih.',
    price: 52000,
    imageUrl: photos.crab,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: 'Bandar Djakarta',
    tags: ['halal', 'high_protein'],
    allergens: ['seafood', 'kedelai'],
    ingredients: ['kerang hijau', 'saus tomat', 'cabai', 'bawang putih'],
    hiddenIngredients: ['saus dapat memakai pengental atau kaldu seafood'],
    sensoryProfile: ['kenyal', 'gurih', 'pedas'],
    crossContaminationRisk: 'Dimasak bersama aneka shellfish.',
    calories: 350,
    prepMinutes: 24,
    sourceUrl: mahi,
  },
  {
    name: 'Lobster Bakar Madu',
    description:
      'Lobster bakar dengan lapisan madu yang manis, gurih, dan smoky.',
    price: 92000,
    imageUrl: photos.crab,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: 'Bandar Djakarta',
    tags: ['high_protein'],
    allergens: ['seafood'],
    ingredients: ['lobster', 'madu', 'bawang putih', 'bumbu bakar'],
    hiddenIngredients: [],
    sensoryProfile: ['juicy', 'manis', 'smoky'],
    crossContaminationRisk: 'Grill digunakan bersama ikan lain.',
    calories: 470,
    prepMinutes: 25,
    sourceUrl: 'https://www.seafoodwatch.org/',
  },
  {
    name: 'Fish and Chips',
    description:
      'Fillet ikan berbalut batter garing dengan kentang dan tartar.',
    price: 57727,
    imageUrl: photos.fish,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: "D'Cost Seafood",
    tags: ['high_protein'],
    allergens: ['seafood', 'gluten', 'telur', 'susu'],
    ingredients: ['ikan dori', 'tepung terigu', 'susu', 'telur', 'kentang'],
    hiddenIngredients: ['telur pada saus tartar', 'susu pada batter'],
    sensoryProfile: ['renyah', 'creamy', 'gurih'],
    crossContaminationRisk: 'Fryer bersama calamari dan udang.',
    calories: 780,
    prepMinutes: 28,
    sourceUrl: 'https://www.allrecipes.com/recipes/411/seafood/fish/',
  },
  {
    name: 'Ikan Soup Kimlo',
    description:
      'Sup ikan hangat dengan sayuran dan kuah kimlo yang gurih ringan.',
    price: 48000,
    imageUrl: photos.soup,
    category: 'soup',
    cluster: 'seafood',
    restaurant: 'Bandar Djakarta',
    tags: ['halal', 'high_protein', 'low_fat'],
    allergens: ['seafood'],
    ingredients: ['ikan', 'sayuran', 'jamur', 'kuah kimlo'],
    hiddenIngredients: [],
    sensoryProfile: ['hangat', 'ringan', 'gurih'],
    crossContaminationRisk: 'Dapur juga menangani shellfish.',
    calories: 280,
    prepMinutes: 25,
    sourceUrl: mahi,
  },
  {
    name: 'Udang Bakar Madu Pedas',
    description: 'Udang bakar juicy dengan lapisan madu, jeruk, dan bawang.',
    price: 72000,
    imageUrl: photos.shrimp,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: 'Bandar Djakarta',
    tags: ['halal', 'high_protein'],
    allergens: ['seafood', 'kedelai'],
    ingredients: ['udang', 'madu', 'kecap asin', 'jeruk nipis'],
    hiddenIngredients: ['kedelai pada kecap'],
    sensoryProfile: ['smoky', 'juicy', 'manis'],
    crossContaminationRisk: 'Panggangan digunakan bersama ikan dan cumi.',
    calories: 410,
    prepMinutes: 27,
    sourceUrl: mahi,
  },
  {
    name: 'Nasi Goreng Seafood',
    description:
      'Nasi goreng wok hei dengan udang, cumi, telur, dan daun bawang.',
    price: 46000,
    imageUrl: photos.rice,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: 'Bandar Djakarta',
    tags: ['halal', 'high_protein'],
    allergens: ['seafood', 'telur', 'kedelai'],
    ingredients: ['nasi', 'udang', 'cumi', 'telur', 'kecap asin'],
    hiddenIngredients: ['kedelai pada kecap'],
    sensoryProfile: ['smoky', 'gurih', 'kenyal'],
    crossContaminationRisk: 'Wok bersama seluruh menu seafood.',
    calories: 610,
    prepMinutes: 18,
    sourceUrl: royco,
  },
  {
    name: 'Nasi Ikan Patin Sambal Tempong',
    description: 'Nasi dengan ikan patin dan sambal tempong yang segar pedas.',
    price: 45000,
    imageUrl: photos.fish,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: "D'Cost Seafood",
    tags: ['high_protein', 'spicy'],
    allergens: ['seafood'],
    ingredients: ['nasi', 'ikan patin', 'cabai', 'tomat', 'jeruk limau'],
    hiddenIngredients: [],
    sensoryProfile: ['gurih', 'pedas', 'segar'],
    crossContaminationRisk: 'Area masak bersama shellfish.',
    calories: 550,
    prepMinutes: 22,
    sourceUrl: 'https://www.allrecipes.com/recipes/416/seafood/fish/tuna/',
  },
  {
    name: 'Chicken Cordon Bleu',
    description:
      'Ayam berisi keju dan smoked beef dengan balutan tepung roti renyah.',
    price: 55455,
    imageUrl: photos.chicken,
    category: 'main_course',
    cluster: 'seafood',
    restaurant: "D'Cost Seafood",
    tags: ['high_protein'],
    allergens: ['susu', 'gluten', 'telur'],
    ingredients: ['ayam', 'keju', 'smoked beef', 'tepung roti', 'telur'],
    hiddenIngredients: ['susu pada keju', 'gluten pada tepung roti'],
    sensoryProfile: ['creamy', 'renyah', 'gurih'],
    crossContaminationRisk:
      'Disiapkan di dapur yang juga menangani ikan dan shellfish.',
    calories: 590,
    prepMinutes: 16,
    sourceUrl: 'https://www.seafoodwatch.org/',
  },
];

async function main() {
  const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
  const prisma = new PrismaClient({ adapter });

  try {
    for (const menu of catalog) {
      const verifiedSourceUrl =
        sourceByMenu[menu.name] ?? sourceByRestaurant[menu.restaurant];
      if (!verifiedSourceUrl) {
        throw new Error(`Sumber resmi belum dipetakan untuk ${menu.name}`);
      }
      const verifiedMenu = {
        ...menu,
        sourceUrl: verifiedSourceUrl,
        priceStatus: officialPriceSnapshots.has(menu.name)
          ? 'official_snapshot_2026_07_11'
          : 'simulated',
      };

      await prisma.menu.upsert({
        where: { name: menu.name },
        update: verifiedMenu,
        create: verifiedMenu,
      });
    }
    console.log(`Seeded ${catalog.length} research menu items.`);
  } finally {
    await prisma.$disconnect();
  }
}

void main();
